apiVersion: v1
kind: Pod
metadata:
  name: test-1
  labels:
    sim.k8s.io/managed: "true"
spec:
  containers:
    - image: nginx
      name: nginx
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"